#!/usr/bin/env bash
# Evaluate trained EPA runs on the SpokenWOZ test split and print Table 1.
#
# Training reports only val accuracy. MRA/HEA/PAR/ERC live in
# ForecastingTrainer.infer_loop, which runs only when the config carries
# infer_params -- i.e. only through configs/infer.yaml, generated by
# make_configs.py. This script drives that for every trained run and then
# reduces the threshold sweep to the paper's table.
#
#   bash scripts/evaluate.sh                 # every run with a checkpoint
#   bash scripts/evaluate.sh fc640 fcall     # only these
#   NGPU=4 bash scripts/evaluate.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODEL_DIR="$ROOT/EndpointAnticipation/anticipation-model"
CKPT_DIR="${CKPT_DIR:-$ROOT/checkpoints}"
# dump may sit on another filesystem; the generated data config is the authority
DUMP_DIR="${DUMP_DIR:-}"
if [ -z "$DUMP_DIR" ] && [ -f "$ROOT/configs/data/swoz_v1.yaml" ]; then
  DUMP_DIR=$(grep -m1 "dump:" "$ROOT/configs/data/swoz_v1.yaml" | sed "s/.*dump:[[:space:]]*//; s/[[:space:]]*$//")
fi
[ -n "$DUMP_DIR" ] || DUMP_DIR="$ROOT/dump"
INFER_CFG="${INFER_CFG:-$ROOT/configs/infer.yaml}"
LOG_DIR="$ROOT/logs/eval"
VENV="${VENV:-$ROOT/.venv}"
PY="$VENV/bin/python"; [ -x "$PY" ] || PY="$VENV/Scripts/python.exe"
NGPU="${NGPU:-$(nvidia-smi --list-gpus 2>/dev/null | wc -l)}"
[ "$NGPU" -ge 1 ] 2>/dev/null || NGPU=1

[ -f "$INFER_CFG" ] || {
  echo "!! $INFER_CFG not found. Generate it:"
  echo "   \$VENV/bin/python scripts/make_configs.py --root $ROOT --num-workers 32"
  exit 1; }

# Inference reads the test split. If it was never preprocessed, the loader will
# silently start channel-splitting + resampling 1000 dialogues -- on the GPU node.
if ! ls "$DUMP_DIR"/*/filtered_test_*.json >/dev/null 2>&1; then
  echo "!! the test split has not been preprocessed."
  echo "   Run this first (CPU job, no GPU):"
  echo "     sbatch scripts/preprocess.sbatch test"
  echo "   Otherwise inference spends hours resampling while holding a GPU."
  exit 1
fi

# discover trained runs; a run is ready when its best checkpoint exists
mapfile -t ALL < <(cd "$CKPT_DIR" && for d in */; do
                     [ -f "${d}best_val_acc.pt" ] && echo "${d%/}"; done)
if [ $# -gt 0 ]; then
  RUNS=()
  for want in "$@"; do
    for r in "${ALL[@]}"; do case "$r" in *"__${want}_"*|*"__${want}") RUNS+=("$r");; esac; done
  done
else
  RUNS=("${ALL[@]}")
fi
[ ${#RUNS[@]} -gt 0 ] || { echo "!! no run with best_val_acc.pt under $CKPT_DIR"; exit 1; }

mkdir -p "$LOG_DIR"
echo "checkpoints : $CKPT_DIR"
echo "infer cfg   : $INFER_CFG"
echo "runs        : ${RUNS[*]}"
echo "gpus        : $NGPU"
echo

i=0
for run in "${RUNS[@]}"; do
  gpu=$(( i % NGPU ))
  log="$LOG_DIR/${run}.log"
  echo "[gpu $gpu] $run -> $log"
  ( cd "$MODEL_DIR" && CUDA_VISIBLE_DEVICES="$gpu" \
      "$PY" run.py --config "$INFER_CFG" --infer "$run" >"$log" 2>&1 ) &
  i=$(( i + 1 ))
  if (( i % NGPU == 0 )); then echo "  -- wave full ($NGPU jobs), waiting --"; wait; fi
done
wait

echo
echo "== Table 1 =="
"$PY" "$ROOT/scripts/report_table1.py" --root "$ROOT" --checkpoints "$CKPT_DIR" \
      --csv "$ROOT/logs/eval/threshold_sweep.csv"
